version: "3.7"

services:
  server:
    environment:
      - "MYSQL_ENV=local"
      - "BRIEEFLY_ENVIRONMENT=local"
    ports:
      - "80:5000"
  db:
    environment:
      - "MYSQL_ENV=local"
      - "BRIEEFLY_ENVIRONMENT=local"
