version: "3.7"

networks:
  network:
    driver: overlay

secrets:
  config_local:
    file: ./secrets/config-local.json

services:
  server:
    image: 127.0.0.1:5000/server
    volumes:
      - ./server:/server
    ports:
      - 5001:443
    depends_on:
      - db
    networks:
      - network
    secrets:
      - config_local
  db:
    image: 127.0.0.1:5000/db
    volumes:
      - ./db:/db
    ports:
      - 5002:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      - network
    secrets:
      - config_local
