version: "3.7"

services:
  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - 5001:443
    depends_on:
      - db

  db:
    build: ./db
    volumes:
      - ./db:/db
    ports:
      - 3306:3306
