version: "3.7"

services:
  db:
    build: ./db
    volumes:
      - ./db:/db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ENV=local
    hostname: db
  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - 443:5001
      - 80:5002
    hostname: server
    stdin_open: true
    depends_on:
      - db
