version: "3.7"

networks:
  net:
    attachable: true

services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    networks:
      - net
  server:
    build: ./server
    networks:
      - net
    tty: true
    links:
      - db:db
